name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
     -  uses: actions/checkout@v1 
        with:
          submodules: true
     - uses: actions/checkout@v2
     - run:  git submodule sync --recursive
     - name: cmake
       run: mkdir build; cd build ;  cmake ..
     - name: make
       run: cd build ; make
